# S3 Resources - Region: eu-north-1
# Generated by AWS Scanner

resource "aws_s3_bucket" "infrasync" {
  bucket = "infrasync"
}

resource "aws_s3_bucket" "serverless_framework_deployments_us_east_1_1e0b675d_952d" {
  bucket = "serverless-framework-deployments-us-east-1-1e0b675d-952d"
}

resource "aws_s3_bucket" "terraformer_test_api_dev_serverlessdeploymentbucke_pwxd2irfmgmi" {
  bucket = "terraformer-test-api-dev-serverlessdeploymentbucke-pwxd2irfmgmi"
}

resource "aws_s3_bucket" "testing_infrasync" {
  bucket = "testing-infrasync"
}

